eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8002
spring:
  datasource:
          driver-class-name: com.mysql.jdbc.Driver
          password: etoak
          url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
          username: root
  application:
    name: service-feign
mybatis:
    mapperLocations: classpath:mapXml/*.xml
    typeAliasesPackage: com.cluster.dao.po
ribbon:
  ReadTimeout: 3000 #请求处理的超时时间
  ConnectTimeout: 3000 #请求连接的超时时间
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试