eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8003
spring:
  thymeleaf:
      suffix: .html
  datasource:
            driver-class-name: com.mysql.jdbc.Driver
            password: etoak
            url: jdbc:mysql://127.0.0.1:3306/shiro?serverTimezone=UTC
            username: root
  application:
    name: service-zuul
  redis:
          database: 1
          # Redis服务器地址
          host: 127.0.0.1
          # Redis服务器连接端口
          port: 6379
          # Redis服务器连接密码（默认为空）
          password:
          # 连接池最大连接数（使用负值表示没有限制）
          pool:
              maxActive: 8
              # 连接池最大阻塞等待时间（使用负值表示没有限制）
              maxWait: -1
              # 连接池中的最大空闲连接
              maxIdle: 8
              # 连接池中的最小空闲连接
              minIdle: 0
          # 连接超时时间（毫秒）
          timeout: 0
          # 默认的数据过期时间，主要用于shiro权限管理
          expire: 2592000
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-feign
    api-b:
      path: /api-b/**
      serviceId: service-feign
mybatis:
    mapperLocations: classpath:mapXml/**/*.xml
    typeAliasesPackage: com.zuul.zuul.dao.po